apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernetes-workshop-access
rules:
- apiGroups:
  - apps
  - extensions
  - networking.k8s.io
  - ""
  resources:
  - pods
  - endpoints
  - namespaces
  - services
  - replicationcontrollers
  - deployments
  - replicasets
  - ingresses
  - pods/log
  - pods/exec
  - pods/portforward
  verbs:
  - get
  - watch
  - list
  - create
  - delete
  - update
  - patch
- apiGroups:
  - apps
  - ""
  - batch
  resources:
  - nodes
  - cronjobs
  - jobs
  - clusterroles
  - clusterrolebindings
  - roles
  - rolebindings
  - configmaps
  verbs:
  - get
  - watch
  - list
